#!/usr/bin/env python3

import os
import shutil
import subprocess
import platform
import json
from pathlib import Path

try:
    from termcolor import colored
except ImportError:
    def colored(text, color=None, attrs=None): return text

# --- Utility Functions ---

def print_step(msg):
    print(colored(f"\n[+] {msg}", "cyan", attrs=["bold"]))

def print_success(msg):
    print(colored(f"  ✓ {msg}", "green"))

def print_error(msg):
    print(colored(f"  ✗ {msg}", "red"))

def run_cmd(cmd, capture=False):
    """Run a shell command safely."""
    try:
        res = subprocess.run(
            cmd, shell=isinstance(cmd, str), check=True,
            capture_output=capture, text=True
        )
        return True, res.stdout if capture else ""
    except subprocess.CalledProcessError as e:
        return False, e.stderr if capture else str(e)

# --- Configuration Sync ---

def sync_config(base_dir: Path, home_dir: Path):
    """Sync dotfiles and Neovim directories."""
    print_step("Syncing Configuration Files")
    
    nvim_src = base_dir / "config" / "nvim"
    nvim_dest = home_dir / ".config" / "nvim"

    # Sync nvim folder
    if nvim_src.exists():
        try:
            nvim_dest.parent.mkdir(parents=True, exist_ok=True)
            if nvim_dest.exists():
                shutil.rmtree(nvim_dest)
            shutil.copytree(nvim_src, nvim_dest)
            print_success("Synced ~/.config/nvim")
        except Exception as e:
            print_error(f"Failed to sync config/nvim: {e}")

# --- Environment Configuration ---

def generate_env_config(base_dir: Path, home_dir: Path):
    """Generates Neovim Lua environment configuration."""
    print_step("Generating Environment Config (env_paths.lua)")
    
    lua_dir = home_dir / ".config" / "nvim" / "lua"
    env_file = lua_dir / "env_paths.lua"
    
    venv_python = base_dir / ".venv" / "bin" / "python3"
    final_python = str(venv_python) if venv_python.exists() else (shutil.which("python3") or "")
    final_node = shutil.which("node") or ""

    try:
        lua_dir.mkdir(parents=True, exist_ok=True)
        content = (
            "-- Auto-generated by setup_vim.py\n"
            "return {\n"
            f'    python_path = "{final_python}",\n'
            f'    node_path = "{final_node}"\n'
            "}\n"
        )
        env_file.write_text(content)
        print_success(f"Generated {env_file}")
    except Exception as e:
        print_error(f"Failed to generate env_paths.lua: {e}")

# --- Plugin Management ---

def install_nvim_plugins():
    """Install plugins, Treesitter parsers, and CoC extensions."""
    print_step("Installing Neovim Plugins (Lazy.nvim)")
    success, _ = run_cmd(["nvim", "--headless", "+Lazy! sync", "+qa"])
    if success:
        print_success("Plugins synced successfully via Lazy.")
    else:
        print_error("Failed to sync plugins via Lazy.")

    print_step("Installing Treesitter Parsers")
    # TSUpdateSync ensures parsers are installed/updated during the setup process
    success, _ = run_cmd(["nvim", "--headless", "+TSUpdateSync", "+qa"])
    if success:
        print_success("Treesitter parsers installed successfully.")
    else:
        print_error("Failed to install Treesitter parsers.")


def install_coc_extensions(base_dir: Path):
    """Install COC extensions from package.json."""
    print_step("Installing coc.nvim Extensions")
    
    pkg_json = base_dir / "coc" / "extensions" / "package.json"
    if not pkg_json.exists():
        print_success("No coc extensions package.json found. Skipping.")
        return

    try:
        data = json.loads(pkg_json.read_text())
        extensions = data.get("dependencies", {}).keys()
        
        for ext in extensions:
            print(f"  Installing {ext}...")
            success, err = run_cmd(["nvim", "--headless", "-c", f"CocInstall -sync {ext}", "-c", "q"], capture=True)
            if success:
                print_success(f"Installed {ext}")
            else:
                print_error(f"Failed to install {ext}: {err}")
    except Exception as e:
        print_error(f"Error processing coc extensions: {e}")

# --- Shell Aliases ---

def add_alias(home_dir: Path):
    """Add vim='nvim' alias to shell config."""
    print_step("Setting up Neovim alias")
    
    alias_cmd = 'alias vim="nvim"'
    shells = [".bashrc", ".zshrc"]
    
    for shell_file in shells:
        shell_rc = home_dir / shell_file
        if not shell_rc.exists():
            continue
            
        try:
            content = shell_rc.read_text()
            if alias_cmd in content or "alias vim='nvim'" in content:
                print_success(f"Alias already exists in {shell_rc.name}")
                continue
                
            with open(shell_rc, "a") as f:
                f.write(f"\n# Alias for Neovim\n{alias_cmd}\n")
            print_success(f"Added alias to {shell_rc.name}")
        except Exception as e:
            print_error(f"Failed to add alias to {shell_rc.name}: {e}")

# --- Main Flow ---

def main():
    base_dir = Path(__file__).parent.resolve()
    home_dir = Path.home()
    
    print(colored("Starting Neovim Auto-Configuration (v2)", "cyan", attrs=["bold", "reverse"]))
    
    sync_config(base_dir, home_dir)
    generate_env_config(base_dir, home_dir)
    install_nvim_plugins()
    install_coc_extensions(base_dir)
    add_alias(home_dir)
    
    print_step("Configuration Completed! 🚀")

if __name__ == "__main__":
    main()
